// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: brand_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createBrand = `-- name: CreateBrand :exec
INSERT INTO brands (id, name, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateBrandParams struct {
	ID          string
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) error {
	_, err := q.db.ExecContext(ctx, createBrand,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteBrand = `-- name: DeleteBrand :exec
UPDATE brands
SET deleted_at = NOW()
WHERE id = ?
`

func (q *Queries) DeleteBrand(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBrand, id)
	return err
}

const getBrand = `-- name: GetBrand :one
SELECT id, name, description, deleted_at, created_at, updated_at FROM brands WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetBrand(ctx context.Context, id string) (Brand, error) {
	row := q.db.QueryRowContext(ctx, getBrand, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandProducts = `-- name: GetBrandProducts :many
SELECT p.id, p.name, p.description, p.price, p.quantity_in_stock, p.image_url, p.category_id, p.brand_id, p.deleted_at, p.created_at, p.updated_at
FROM brands b
JOIN products p ON b.id = p.brand_id
WHERE b.id = ? AND b.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY p.name
`

func (q *Queries) GetBrandProducts(ctx context.Context, id string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getBrandProducts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.QuantityInStock,
			&i.ImageUrl,
			&i.CategoryID,
			&i.BrandID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, description, deleted_at, created_at, updated_at
FROM brands
WHERE deleted_at IS NULL
ORDER BY name
LIMIT ? OFFSET ?
`

type ListBrandsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBrands(ctx context.Context, arg ListBrandsParams) ([]Brand, error) {
	rows, err := q.db.QueryContext(ctx, listBrands, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrand = `-- name: UpdateBrand :exec
UPDATE brands
SET name = ?, description = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateBrandParams struct {
	Name        string
	Description sql.NullString
	UpdatedAt   sql.NullTime
	ID          string
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) error {
	_, err := q.db.ExecContext(ctx, updateBrand,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
