// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Brand struct {
	ID          string
	Name        string
	Description sql.NullString
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Category struct {
	ID          string
	Name        string
	Description sql.NullString
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Coupon struct {
	ID           string
	Code         string
	Discount     float64
	ExpirationAt time.Time
	Status       string
	DeletedAt    sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Customer struct {
	ID        string
	Name      string
	Email     string
	Password  string
	Address   sql.NullString
	Phone     sql.NullString
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Delivery struct {
	ID             string
	OrderID        sql.NullString
	CustomerID     sql.NullString
	DeliveryType   string
	DeliveryAt     sql.NullTime
	DeliveryStatus string
	DeletedAt      sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Feedback struct {
	ID         string
	CustomerID sql.NullString
	OrderID    sql.NullString
	Rating     sql.NullInt32
	Comment    sql.NullString
	DeletedAt  sql.NullTime
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Order struct {
	ID          string
	CustomerID  sql.NullString
	OrderAt     sql.NullTime
	OrderStatus string
	TotalValue  float64
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type OrderItem struct {
	ID        string
	OrderID   sql.NullString
	ProductID sql.NullString
	Quantity  int32
	UnitPrice float64
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type OrderProduct struct {
	ID        string
	OrderID   sql.NullString
	ProductID sql.NullString
	Quantity  int32
	UnitPrice float64
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Payment struct {
	ID            string
	OrderID       sql.NullString
	CustomerID    sql.NullString
	PaymentType   string
	PaymentAt     sql.NullTime
	PaymentValue  float64
	PaymentStatus string
	DeletedAt     sql.NullTime
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Product struct {
	ID              string
	Name            string
	Description     sql.NullString
	Price           float64
	QuantityInStock int32
	ImageUrl        sql.NullString
	CategoryID      sql.NullString
	BrandID         sql.NullString
	DeletedAt       sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ProductStock struct {
	ID        string
	ProductID sql.NullString
	StockID   sql.NullString
	Quantity  int32
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Stock struct {
	ID        string
	Name      string
	Location  sql.NullString
	Capacity  int32
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
