// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Brand struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Category struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Coupon struct {
	ID           uuid.UUID
	Code         string
	Discount     float64
	ExpirationAt time.Time
	Status       string
	DeletedAt    sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Customer struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Address   sql.NullString
	Phone     sql.NullString
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Delivery struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	CustomerID     uuid.UUID
	DeliveryType   string
	DeliveryAt     sql.NullTime
	DeliveryStatus string
	DeletedAt      sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Feedback struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	OrderID    uuid.UUID
	Rating     sql.NullInt32
	Comment    sql.NullString
	DeletedAt  sql.NullTime
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Order struct {
	ID          uuid.UUID
	CustomerID  uuid.UUID
	OrderAt     sql.NullTime
	OrderStatus string
	TotalValue  float64
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type OrderItem struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	UnitPrice float64
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type OrderProduct struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	UnitPrice float64
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Payment struct {
	ID            uuid.UUID
	OrderID       uuid.UUID
	CustomerID    uuid.UUID
	PaymentType   string
	PaymentAt     sql.NullTime
	PaymentValue  float64
	PaymentStatus string
	DeletedAt     sql.NullTime
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Product struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	Price           float64
	QuantityInStock int32
	ImageUrl        sql.NullString
	CategoryID      uuid.UUID
	BrandID         uuid.UUID
	DeletedAt       sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ProductStock struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	StockID   uuid.UUID
	Quantity  int32
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Stock struct {
	ID        uuid.UUID
	Name      string
	Location  sql.NullString
	Capacity  int32
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
