// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	common "github.com/becardine/gestock-api/internal/domain/entity/common"
	"github.com/google/uuid"
)

type Brand struct {
	ID          common.ID
	Name        string
	Description sql.NullString
	DeletedAt   sql.NullTime
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}

type Category struct {
	ID          common.ID
	Name        string
	Description sql.NullString
	DeletedAt   sql.NullTime
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}

type Coupon struct {
	ID             common.ID
	Code           string
	Discount       string
	ExpirationDate time.Time
	Status         string
	DeletedAt      sql.NullTime
	CreatedDate    sql.NullTime
	UpdatedDate    sql.NullTime
}

type Customer struct {
	ID          common.ID
	Name        string
	Email       string
	Password    string
	Address     sql.NullString
	Phone       sql.NullString
	DeletedAt   sql.NullTime
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}

type Delivery struct {
	ID             common.ID
	OrderID        uuid.NullUUID
	CustomerID     uuid.NullUUID
	DeliveryType   string
	DeliveryDate   sql.NullTime
	DeliveryStatus string
	DeletedAt      sql.NullTime
	CreatedDate    sql.NullTime
	UpdatedDate    sql.NullTime
}

type Feedback struct {
	ID          common.ID
	CustomerID  uuid.NullUUID
	OrderID     uuid.NullUUID
	Rating      sql.NullInt32
	Comment     sql.NullString
	DeletedAt   sql.NullTime
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}

type Order struct {
	ID          common.ID
	CustomerID  uuid.NullUUID
	OrderDate   sql.NullTime
	OrderStatus string
	TotalValue  string
	DeletedAt   sql.NullTime
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}

type OrderProduct struct {
	ID          common.ID
	OrderID     uuid.NullUUID
	ProductID   uuid.NullUUID
	Quantity    int32
	UnitPrice   string
	DeletedAt   sql.NullTime
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}

type Payment struct {
	ID            common.ID
	OrderID       uuid.NullUUID
	CustomerID    uuid.NullUUID
	PaymentType   string
	PaymentDate   sql.NullTime
	PaymentValue  string
	PaymentStatus string
	DeletedAt     sql.NullTime
	CreatedDate   sql.NullTime
	UpdatedDate   sql.NullTime
}

type Product struct {
	ID              common.ID
	Name            string
	Description     sql.NullString
	Price           string
	QuantityInStock int32
	ImageUrl        sql.NullString
	CategoryID      uuid.NullUUID
	BrandID         uuid.NullUUID
	DeletedAt       sql.NullTime
	CreatedDate     sql.NullTime
	UpdatedDate     sql.NullTime
}

type ProductStock struct {
	ID          common.ID
	StockID     common.ID
	ProductID   common.ID
	DeletedAt   sql.NullTime
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}

type Stock struct {
	ID          common.ID
	Name        string
	Location    sql.NullString
	Capacity    int32
	DeletedAt   sql.NullTime
	CreatedDate sql.NullTime
	UpdatedDate sql.NullTime
}
