// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: product_stocks_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createProductStock = `-- name: CreateProductStock :exec
INSERT INTO product_stocks (
    id, product_id, stock_id, quantity, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateProductStockParams struct {
	ID        string
	ProductID sql.NullString
	StockID   sql.NullString
	Quantity  int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateProductStock(ctx context.Context, arg CreateProductStockParams) error {
	_, err := q.db.ExecContext(ctx, createProductStock,
		arg.ID,
		arg.ProductID,
		arg.StockID,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProductStock = `-- name: DeleteProductStock :exec
UPDATE product_stocks
SET deleted_at = NOW()
WHERE product_id = ? AND stock_id = ?
`

type DeleteProductStockParams struct {
	ProductID sql.NullString
	StockID   sql.NullString
}

func (q *Queries) DeleteProductStock(ctx context.Context, arg DeleteProductStockParams) error {
	_, err := q.db.ExecContext(ctx, deleteProductStock, arg.ProductID, arg.StockID)
	return err
}

const getProductStock = `-- name: GetProductStock :one
SELECT id, product_id, stock_id, quantity, deleted_at, created_at, updated_at
FROM product_stocks
WHERE product_id = ? AND stock_id = ? AND deleted_at IS NULL
`

type GetProductStockParams struct {
	ProductID sql.NullString
	StockID   sql.NullString
}

func (q *Queries) GetProductStock(ctx context.Context, arg GetProductStockParams) (ProductStock, error) {
	row := q.db.QueryRowContext(ctx, getProductStock, arg.ProductID, arg.StockID)
	var i ProductStock
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StockID,
		&i.Quantity,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductStocks = `-- name: ListProductStocks :many
SELECT id, product_id, stock_id, quantity, deleted_at, created_at, updated_at
FROM product_stocks
WHERE product_id = ? AND deleted_at IS NULL
ORDER BY created_at
LIMIT 2 OFFSET 3
`

func (q *Queries) ListProductStocks(ctx context.Context, productID sql.NullString) ([]ProductStock, error) {
	rows, err := q.db.QueryContext(ctx, listProductStocks, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductStock
	for rows.Next() {
		var i ProductStock
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StockID,
			&i.Quantity,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsInStock = `-- name: ListProductsInStock :many
SELECT p.id, p.name, p.description, p.price, p.quantity_in_stock, p.image_url, p.category_id, p.brand_id, p.deleted_at, p.created_at, p.updated_at
FROM products p
JOIN product_stocks ps ON p.id = ps.product_id
WHERE ps.stock_id = ? AND ps.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY p.name
LIMIT 2 OFFSET 3
`

func (q *Queries) ListProductsInStock(ctx context.Context, stockID sql.NullString) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsInStock, stockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.QuantityInStock,
			&i.ImageUrl,
			&i.CategoryID,
			&i.BrandID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE product_stocks
SET quantity = ?, updated_at = ?
WHERE product_id = ? AND stock_id = ? AND deleted_at IS NULL
`

type UpdateProductStockParams struct {
	Quantity  int32
	UpdatedAt sql.NullTime
	ProductID sql.NullString
	StockID   sql.NullString
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.ExecContext(ctx, updateProductStock,
		arg.Quantity,
		arg.UpdatedAt,
		arg.ProductID,
		arg.StockID,
	)
	return err
}
