-- Remove  all tables
DROP TABLE IF EXISTS order_products;
DROP TABLE IF EXISTS feedbacks;
DROP TABLE IF EXISTS coupons;
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS brands;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS stocks;
DROP TABLE IF EXISTS products;
DROP IF EXISTS TABLE product_stocks;