// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delivery_queries.sql

package db

import (
	"context"
	"database/sql"

	common "github.com/becardine/gestock-api/internal/entity/common"
	"github.com/google/uuid"
)

const createDelivery = `-- name: CreateDelivery :exec
INSERT INTO deliveries (id, order_id, customer_id, delivery_type, delivery_date, delivery_status, created_date, updated_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateDeliveryParams struct {
	ID             common.ID
	OrderID        uuid.NullUUID
	CustomerID     uuid.NullUUID
	DeliveryType   string
	DeliveryDate   sql.NullTime
	DeliveryStatus string
	CreatedDate    sql.NullTime
	UpdatedDate    sql.NullTime
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, createDelivery,
		arg.ID,
		arg.OrderID,
		arg.CustomerID,
		arg.DeliveryType,
		arg.DeliveryDate,
		arg.DeliveryStatus,
		arg.CreatedDate,
		arg.UpdatedDate,
	)
	return err
}

const deleteDelivery = `-- name: DeleteDelivery :exec
UPDATE deliveries
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteDelivery(ctx context.Context, id common.ID) error {
	_, err := q.db.ExecContext(ctx, deleteDelivery, id)
	return err
}

const getDeliveriesByCustomerId = `-- name: GetDeliveriesByCustomerId :many
SELECT id, order_id, customer_id, delivery_type, delivery_date, delivery_status, deleted_at, created_date, updated_date
FROM deliveries
WHERE customer_id = $1 AND deleted_at IS NULL
ORDER BY delivery_date DESC
`

func (q *Queries) GetDeliveriesByCustomerId(ctx context.Context, customerID uuid.NullUUID) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, getDeliveriesByCustomerId, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CustomerID,
			&i.DeliveryType,
			&i.DeliveryDate,
			&i.DeliveryStatus,
			&i.DeletedAt,
			&i.CreatedDate,
			&i.UpdatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveriesByOrderId = `-- name: GetDeliveriesByOrderId :many
SELECT id, order_id, customer_id, delivery_type, delivery_date, delivery_status, deleted_at, created_date, updated_date
FROM deliveries
WHERE order_id = $1 AND deleted_at IS NULL
ORDER BY delivery_date DESC
`

func (q *Queries) GetDeliveriesByOrderId(ctx context.Context, orderID uuid.NullUUID) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, getDeliveriesByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CustomerID,
			&i.DeliveryType,
			&i.DeliveryDate,
			&i.DeliveryStatus,
			&i.DeletedAt,
			&i.CreatedDate,
			&i.UpdatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, order_id, customer_id, delivery_type, delivery_date, delivery_status, deleted_at, created_date, updated_date FROM deliveries WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDelivery(ctx context.Context, id common.ID) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.DeliveryType,
		&i.DeliveryDate,
		&i.DeliveryStatus,
		&i.DeletedAt,
		&i.CreatedDate,
		&i.UpdatedDate,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, order_id, customer_id, delivery_type, delivery_date, delivery_status, deleted_at, created_date, updated_date FROM deliveries WHERE deleted_at IS NULL ORDER BY delivery_date DESC
`

func (q *Queries) ListDeliveries(ctx context.Context) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CustomerID,
			&i.DeliveryType,
			&i.DeliveryDate,
			&i.DeliveryStatus,
			&i.DeletedAt,
			&i.CreatedDate,
			&i.UpdatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDelivery = `-- name: UpdateDelivery :exec
UPDATE deliveries
SET order_id = $2, customer_id = $3, delivery_type = $4, delivery_date = $5, delivery_status = $6, updated_date = $7
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateDeliveryParams struct {
	ID             common.ID
	OrderID        uuid.NullUUID
	CustomerID     uuid.NullUUID
	DeliveryType   string
	DeliveryDate   sql.NullTime
	DeliveryStatus string
	UpdatedDate    sql.NullTime
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, updateDelivery,
		arg.ID,
		arg.OrderID,
		arg.CustomerID,
		arg.DeliveryType,
		arg.DeliveryDate,
		arg.DeliveryStatus,
		arg.UpdatedDate,
	)
	return err
}
